// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "./providers/NextAuthProvider"; // <<< Import Provider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* ใช้ Provider ครอบ Navbar และ Children */}
        <NextAuthProvider> {/* <<< ครอบด้วย Provider */}
            <Navbar />
            <main>{children}</main>
            {/* Footer etc. */}
        </NextAuthProvider> {/* <<< ปิด Provider */}
      </body>
    </html>
  );
}