// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"; // Import Footer
import NextAuthProvider from "./providers/NextAuthProvider"; // <<< Import Provider
import { ThemeProvider } from "./providers/ThemeProvider"; // Import ThemeProvider


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    // --> ตรวจสอบว่าไม่มีช่องว่าง หรือ Comment ตรงนี้
    <html lang="en" className="h-full" suppressHydrationWarning>
      {/* --> ตรวจสอบว่าไม่มีช่องว่าง หรือ Comment ตรงนี้ */}
      <head>
        {/* Metadata, links, etc. */}
      </head>
      {/* --> ตรวจสอบว่าไม่มีช่องว่าง หรือ Comment ตรงนี้ */}
      <body className={`${inter.className} flex flex-col min-h-full bg-white text-slate-900 dark:bg-slate-900 dark:text-slate-100`}>
        {/* Providers และ Content อยู่ใน body ทั้งหมด */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NextAuthProvider>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </NextAuthProvider>
        </ThemeProvider>
      </body>
      {/* --> ตรวจสอบว่าไม่มีช่องว่าง หรือ Comment ตรงนี้ */}
    </html>
    // --> ตรวจสอบว่าไม่มีช่องว่าง หรือ Comment ตรงนี้
  );
}